version: '2'
services:
  node:
    build: '.'
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "/tmp/vault:/tmp/vault"
  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "127.0.0.1:8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "s0me-d3v-t0k3n"
