// Generated by CoffeeScript 2.0.2
(function() {
  var options, vault;

  options = {
    token: 's0me-d3v-t0k3',
    //apiVersion: 'v1' #default
    endpoint: 'http://vault:8200'
  };

  vault = require("node-vault")(options);

  vault.write('secret/hello', {
    value: 'some',
    lease: '1s'
  }).then(function() {
    return vault.read('secret/hello').then(function(result) {
      return console.log(result);
    });
  }).catch(console.error);

}).call(this);
