// Generated by CoffeeScript 2.0.2
(function() {
  var crypto, file, fs, string;

  crypto = require('crypto');

  fs = require('fs');

  file = process.argv[2];

  string = crypto.randomBytes(32);

  fs.writeFileSync(file, string);

}).call(this);
