// Generated by CoffeeScript 2.0.2
(function() {
  var Key, encrypted_token, fs, key, options, token, vault;

  fs = require('fs');

  Key = require('./key');

  key = new Key(fs.readFileSync('/tmp/vault/key'));

  encrypted_token = fs.readFileSync('/tmp/vault/token').toString();

  token = key.decrypt(encrypted_token);

  options = {
    token: token,
    endpoint: fs.readFileSync('/tmp/vault/address').toString().trim()
  };

  console.log(options);

  vault = require("node-vault")(options);

  vault.write('secret/hello', {
    value: 'some',
    lease: '1s'
  }).then(function() {
    return vault.read('secret/hello').then(function(result) {
      return console.log(result);
    });
  }).then(function() {
    return console.log(vault.delete('secret/hello'));
  }).catch(console.error);

}).call(this);
