// Generated by CoffeeScript 2.0.2
(function() {
  var options, vault;

  options = {
    token: 's0me-d3v-t0k3n'
  };

  //apiVersion: 'v1' #default
  //endpoint: 'http://127.0.0.1:8200' #default
  vault = require("node-vault")(options);

  vault.write('secret/hello', {
    value: 'some',
    lease: '1s'
  }).then(function() {
    return vault.read('secret/hello').then(function(result) {
      return console.log(result);
    });
  }).then(function() {
    return console.log(vault.delete('secret/hello'));
  }).catch(console.error);

}).call(this);
